$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1395119497747.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"11a05cd2c9314a668e0f3d5e95cc943d",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c37755bd90da4e18a7ca918352c7a850",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":0},
            "size":{
              "width":200,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"886d601257f64b71a651843fd67ca8ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":200,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c37755bd90da4e18a7ca918352c7a850":{
      "scriptId":"u0"},
    "886d601257f64b71a651843fd67ca8ee":{
      "scriptId":"u1"}}});